name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv (exactly like local)
        run: |
          uv add pybaseball
          uv add pytest pytest-asyncio
          uv pip install -e .

      - name: Fix pybaseball data files
        run: |
          uv run python mlb_stats_mcp/utils/scripts/data_download.py

      - name: Run tests
        run: |
          uv run pytest -v -k "not (test_get_pitching_stats_bref or test_get_pitching_stats_range or test_get_schedule_and_record or test_get_player_splits)"
        env:
          SHOW_IMAGE: false
